SPK_NAME = lrzsz
SPK_VERS = 0.12.20
SPK_REV = 1
SPK_ICON = src/lrzsz.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = freesmall
DESCRIPTION = free x/y/zmodem implementation
DISPLAY_NAME = lrzsz
STARTABLE = no

HOMEPAGE = https://ohse.de/uwe/software/lrzsz.html
LICENSE = GNU

SPK_COMMANDS = bin/lrz bin/lsz

include ../../mk/spksrc.spk.mk
